### ISSUE TITLE
New Pinacle logo

### ISSUE THREAD

**Issue by shenskie** [forloop-/redesigned-barnacle#10]
![pinaclelogo](https://cloud.githubusercontent.com/assets/15201244/17354102/97cb7530-5956-11e6-9146-70c288685fd0.png)
![pinacletransparent](https://cloud.githubusercontent.com/assets/15201244/17354103/97cee6f2-5956-11e6-95de-e940623f899a.png)

**Comment by forloop-** [comment]
Updated site with new logo.
