### ISSUE TITLE
Independent scrolling 

### ISSUE THREAD

**Issue by shenskie** [forloop-/redesigned-barnacle#5]
Make column to scroll independently. 

When scrolling the content, the column on the right side with forms should stay as it is. Like the screenshot I attached.

<img width="1438" alt="screen shot 2016-07-30 at 3 32 49 pm" src="https://cloud.githubusercontent.com/assets/15201244/17270087/2be84bba-566b-11e6-9777-c65b32df419f.png">

**Comment by forloop-** [comment]
@shenskie , updated. Please check.
