### ISSUE TITLE
Scrolling images

### ISSUE THREAD

**Issue by shenskie** [forloop-/redesigned-barnacle#7]
Add some images and text on the scrolling section of the front page.

Australia:
Australia is committed to build Australia’s future through the well-managed movement of people.

Denmark:
Despite a strong economy, Denmark has not been immune to the international financial crisis and its negative impact on the employment situation.

Hongkong:
Hong Kong, a former British colony and currently a Special Administrative Region (SAR) of China, is a global financial centre with world-class transport infrastructure, port management and logistics services.

South Africa:
South Africa is ranked as an upper-middle income economy by the World Bank, and is considered to be a newly industrialized country.

Canada:
One of the most positive immigration policies in the world in terms of standards of living, the UN has voted Canada as one of the best places in the world to live.

Germany:
One of the wealthiest and largest countries in the European Union (EU), the abundance of jobs and the thriving economy are what makes working in Germany so appealing.

New Zealand:
Pinacle also employs and works with regulated & accredited immigration lawyers in our own offices in London & Canada and partner offices in Australia and New Zealand.

https://drive.google.com/open?id=0B67EKrMsuQk2aGxqRXYzdFZPM28

**Comment by forloop-** [comment]
Text were unreadable after changing the slide images so I tried adding background overlay to make the text readable. 

![screen shot 2016-08-02 at 2 14 43 am](https://cloud.githubusercontent.com/assets/8325640/17310700/0d75f39c-5857-11e6-926c-0800f5262951.png)

What do you think?

**Comment by shenskie** [comment]
Can you try and use a different color for the overlay?

**Comment by forloop-** [comment]
![slider](https://cloud.githubusercontent.com/assets/8325640/17321529/10ff2148-58aa-11e6-8819-c46794326665.gif)

@shenskie is this better? Any suggestion for the color?

**Comment by shenskie** [comment]
Overlay color looks ok.
