### ISSUE TITLE
Text is too big

### ISSUE THREAD

**Issue by shenskie** [forloop-/redesigned-barnacle#8]
http://pinaclevisas-isprototypeof.rhcloud.com/hong-kong-immigration/

Correct typo "HonkKong" 

<img width="842" alt="screen shot 2016-08-01 at 6 34 17 pm" src="https://cloud.githubusercontent.com/assets/15201244/17298013/48211ef6-5819-11e6-971a-c1583ec62c2d.png">

**Comment by forloop-** [comment]
Updated
